Keeping Icon focus state only for keyboard
lensapp/lens pull request #1234
Opened 2020-11-05 13:53 UTC by aleksfront

Removing `:focus` styles for `<Icon />` component when using mouse. This fixes issue when Icon seems frozen in hover state even if cursor went away.

Determining mouse/keyboard usage by toggling `.mouse-intent` class name on `body` element.

Added outline styling for Icon's `:focus` state.

![keyboard focusing](https://user-images.githubusercontent.com/9607060/98249151-fd426e00-1f86-11eb-8a9d-e1fc24defbf7.gif)
![mouse focusing](https://user-images.githubusercontent.com/9607060/98249173-03384f00-1f87-11eb-9543-abcb2c538d61.gif)

Close #1228

2020-11-05 14:03 UTC, ixrock requested changes

2020-11-05 14:03 UTC, ixrock commented on src/renderer/components/layout/main-layout.tsx
> +    window.addEventListener("click", (evt) => {
Why this is in `MainLayout`? 
In addition there is no unbind events in `componentWillUnmount`..

2020-11-05 14:03 UTC, ixrock commented on src/renderer/components/layout/main-layout.tsx
> +    window.addEventListener("click", (evt) => {
Plus it's better to keep it close to `icon` component if it's related only to this.

2020-11-10 07:59 UTC, aleksfront commented
@ixrock Please do re-review. Replaced custom solution with `what-input` dependency which could track used input device
https://www.npmjs.com/package/what-input
https://bundlephobia.com/result?p=what-input@5.2.10

2020-11-10 09:00 UTC, ixrock approved these changes

2020-11-10 09:36 UTC, merged