Fix Ctrl+Q bug
lensapp/lens pull request #1415
Opened 2020-11-17 10:40 UTC by pashevskii

Hi, I found some issues related to not-working Ctrl+Q/File->Quit flows
So, It seems the deal in the wrong event, where the system prevents app.exit() call on windows closing.

The fix is tested on Ubuntu, in theory, it should not affect Mac users because of app.exit() calling on Ctrl+Q

2020-11-17 11:17 UTC, ixrock requested changes
This is done to be able to handle async events when app is closing:
```
event.preventDefault(); // prevent app's default shutdown (e.g. required for telemetry, etc.)
```
In `Windows` menu there is a bug in `File -> Close` item (should be re-used from `macAppMenu`, see: `menu.ts`)

2020-11-17 13:26 UTC, pashevskii commented
Hi @ixrock, thank you for your answer, sorry, it seems there is some misunderstanding from my side...
I suppose that in this case event.preventDefault() function fully prevents termination process, isn't it? 
I think we should terminate the app after  Ctrl+Q instead of just closing the window
As an option we can call app.exit() after clusterManager?.stop() line, it will stop clusters and terminate app.

2020-11-17 13:46 UTC, nevalla commented
I did some renaming of File menu items in #1420. They should now reflect better the role of those items.

2020-11-18 09:17 UTC, pashevskii commented
Looked throw  @nevalla  PRs, It seems he has fixed this problem. I'll close the PR

2020-11-18 09:17 UTC, closed without merging