make LensExtension abstract as an affordence to extension devs
lensapp/lens pull request #1455
Opened 2020-11-19 17:37 UTC by Nokel81

I believe that LensExtension should be `abstract` as the two methods (`onActivate` and `onDeactivate`) both really should be implemented (even for simple extensions).

This would also be a very good affordance to extension developers to remind them that these two methods exist and initializing items that are used only for the duration of the extension's lifetime should be created and deleted within these (instead of in the constructor).

Signed-off-by: Sebastian Malton <sebastian@malton.name>

2020-11-20 07:08 UTC, panuhorsmalahti approved these changes

2020-11-20 07:17 UTC, jakolehm commented
> I believe that LensExtension should be abstract as the two methods (onActivate and onDeactivate) both really should be implemented (even for simple extensions).

I'm not convinced, this changes whole lifecycle of an extension. Currently all registrations happen outside of `onActivate`, if we force developers to define `onActivate` then do we also force all registration happen there? That's like huuuge change how extensions work.

2020-11-20 07:19 UTC, jakolehm requested changes
Blocking this so that we don't accidentally merge.

2020-11-20 16:17 UTC, Nokel81 commented
Okay, I understand that I wasn't that clear with my reasoning behind this change. The main point of this was merely to try and push developers to implementing those functions and to not have their own constructor at all.

2020-11-25 16:17 UTC, Nokel81 commented
Also @jakolehm Abstract classes in javascript can have fields and can have those fields have initializes so this wouldn't change that. However, it does change some other things (related to constructors). So I will close this as it is more work than what we probably want to do.

2020-11-25 16:17 UTC, closed without merging