Fix: allowing to pass any array into virtual list table
lensapp/lens pull request #1537
Opened 2020-11-26 12:39 UTC by aleksfront

This will allow extensions to use `Table` component with `virtual` mode. Currently all items passed into Virtual list must conform `ItemObject` containing `getId()` & `getName()` methods. That's not always the case.

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

2020-11-26 12:51 UTC, panuhorsmalahti approved these changes

2020-11-26 13:03 UTC, ixrock approved these changes

2020-11-26 13:03 UTC, ixrock commented on src/renderer/components/virtual-list/virtual-list.tsx
> +  const uid = items[index].getId ? items[index].getId() : index;
How you can be sure you're that you are checking `getId` from object when you defined items as `any: []`?
```suggestion
  const uid = items[index]?.getId() ?? index;
```

2020-11-26 13:03 UTC, ixrock commented on src/renderer/components/virtual-list/virtual-list.tsx
> +  items: any[];
Maybe this also works? Or even without `| any`

```suggestion
interface Props<T = ItemObject | any> {
  items: T[];
```

2020-11-26 13:16 UTC, Nokel81 commented on src/renderer/components/virtual-list/virtual-list.tsx
> +  const uid = items[index].getId ? items[index].getId() : index;
If `getId` is optionally present, shouldn't it be the following?
```suggestion
  const uid = items[index]?.getId?.() ?? index;
```

2020-11-26 13:27 UTC, panuhorsmalahti commented on src/renderer/components/virtual-list/virtual-list.tsx
> +  const uid = items[index].getId ? items[index].getId() : index;
The original code is (also) correct. getId will return undefined if it's not a property of the object, which is falsy, so indecx would be used in that case. I don't see how null coalescing operator is more readable than the conditional operator. (I think they're equivalent readability wise).

2020-11-26 13:34 UTC, jakolehm approved these changes

2020-11-27 11:47 UTC, aleksfront commented
@panuhorsmalahti @ixrock Made more generic changes to `Table` and `VirtualList` components, please re-review this time.

2020-11-30 09:10 UTC, jakolehm requested changes
I think we should rethink this. It causes a breaking change to `Table` component but actually it might be better to create a new component called `VirtualTable` that is designed for just virtual use cases and mark `virtual` property in `Table` as deprecated.

2020-12-21 08:45 UTC, aleksfront commented
Closing this in favor of separating `Table` and `VirtualTable` components in other PR.

2020-12-21 08:45 UTC, closed without merging