Bug/178 All namespaces show as not allowed
lensapp/lens pull request #204
Opened 2020-04-02 04:56 UTC by clbiggs

When calling the SelfSubjectAccessReview api it appears that the resource needs to be 'pods' instead of 'pod'.
I compared it to the `kubectl can-i list pod --namespace={ns}` which returns yes for me and it always sends 'pods' as the resource.

Fixes #178

2020-04-02 05:20 UTC, jakolehm requested changes
Thanks for the fix! DCO bot is still not happy (git commit sign-off is missing), otherwise LGTM.

2020-04-02 08:51 UTC, zeeZ commented
`pod` vs `pods` does indeed make a difference, but **only if the user is not admin**!

As admin:
```yaml
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
metadata:
  creationTimestamp: null
spec:
  resourceAttributes:
    namespace: kube-system
    resource: pod
    verb: list
status:
  allowed: true
```

As normal user:
```yaml
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
metadata:
  creationTimestamp: null
spec:
  resourceAttributes:
    namespace: default
    resource: pod
    verb: list
status:
  allowed: false
```

Using `pods` instead of `pod` as a normal user:
```yaml
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
metadata:
  creationTimestamp: null
spec:
  resourceAttributes:
    namespace: default
    resource: pods
    verb: list
status:
  allowed: true
  reason: 'RBAC: allowed by ClusterRoleBinding "redacted" of ClusterRole
    "view" to Group "redacted"'
```

2020-04-03 05:22 UTC, jakolehm commented
> Thanks for the fix! DCO bot is still not happy (git commit sign-off is missing), otherwise LGTM.

@clbiggs did you notice this? ^

2020-04-03 16:44 UTC, jakolehm approved these changes

2020-04-03 16:44 UTC, merged