Fix: load releases for all namespaces at once
lensapp/lens pull request #2139
Opened 2021-02-12 13:03 UTC by aleksfront

Load releases for all namespaces at once if `All namespaces` context is selected

https://user-images.githubusercontent.com/9607060/107771327-a994ad00-6d4b-11eb-968e-71a930b71311.mp4
 
Fixes #2137 

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

2021-02-12 14:04 UTC, Nokel81 requested changes

2021-02-12 14:04 UTC, Nokel81 commented on src/renderer/components/+apps-releases/release.store.ts
> +    if (isLoadingAll) {
This is to prevent a similar regression that I found in `kube-object-store.ts`. See #2142 

```suggestion
    if (isLoadingAll && namespaceStore.context.cluster.accessibleNamesapces.length === 0) {
```

2021-02-15 03:07 UTC, aleksfront commented on src/renderer/components/+apps-releases/release.store.ts
> +    if (isLoadingAll) {
Thanks for spotting! Fixed.

2021-02-15 08:17 UTC, nevalla commented
Lens 4.1 set default namespace selected as default, so I think the inital view should reflect on what's selected in namespace filter. Now releases from all namespaces are displayed.

2021-02-15 09:35 UTC, aleksfront commented
> Lens 4.1 set default namespace selected as default, so I think the inital view should reflect on what's selected in namespace filter. Now releases from all namespaces are displayed.

There was 1 missed `loadAll()` call without namespace arguments. Fixed.

2021-02-15 09:37 UTC, aleksfront commented
https://user-images.githubusercontent.com/9607060/107929257-72f8a580-6f8a-11eb-9ba3-fcc829f77465.mp4

2021-02-15 14:25 UTC, ixrock approved these changes
Haven't tested it in runtime, code LGTM.

2021-02-15 14:25 UTC, ixrock commented on src/renderer/components/+apps-releases/release.store.ts
> +    const noAccessibleNamespaces = namespaceStore.context.cluster.accessibleNamespaces.length === 0;
Logic duplication from `KubeObjectStore.loadItems()`.. Maybe extract to upper level? (e.g. `ItemStore`) or reuse somehow in other way..

2021-02-15 19:13 UTC, nevalla approved these changes
LGTM

2021-02-16 14:50 UTC, Nokel81 approved these changes

2021-02-16 14:53 UTC, merged