Fix hotbar light theme colors
lensapp/lens pull request #2943
Opened 2021-06-03 08:36 UTC by vshakirova

Wdyt?
![Screenshot from 2021-06-03 12-30-16](https://user-images.githubusercontent.com/38247153/120613644-78a9c680-c467-11eb-9442-070a3702539c.png)

Suggestion: change `tableHeaderBackground` for themes consistency
![photo_2021-06-03_12-29-18](https://user-images.githubusercontent.com/38247153/120613792-9d9e3980-c467-11eb-9792-f7b334f59100.jpg)
![photo_2021-06-03_12-29-21](https://user-images.githubusercontent.com/38247153/120613796-9ecf6680-c467-11eb-8baa-455d14b1c0e8.jpg)

Wdyt?

fixes: https://github.com/lensapp/lens/issues/2786

2021-06-03 14:07 UTC, Nokel81 submitted a review, later dismissed

2021-06-07 09:28 UTC, aleksfront requested changes
Along with other comments, please add new value for light theme
```
"clusterMenuCellBackground": "#bbbbbb"
```

for dark theme
```
"clusterMenuCellBackground": "#2e3136"
```

and use it for hotbar menu empty cells

![hotbar menu](https://user-images.githubusercontent.com/9607060/120993002-cede7880-c78b-11eb-8aa4-589f6ace38df.png)

2021-06-07 09:28 UTC, aleksfront commented on src/renderer/themes/lens-light.json
> +    "layoutBackground": "#d6d6d6",
Please do not change this one. It affects topbars across the dashboard.

2021-06-07 09:28 UTC, aleksfront commented on src/renderer/themes/lens-light.json
> +    "tableHeaderBackground": "#ffffff",
It affects general tables style. It was better with "grayed" table head.

Tables before the change:
![gray table head](https://user-images.githubusercontent.com/9607060/120992289-216b6500-c78b-11eb-8ae9-e559286a113d.png)

Tables after the change:
![white table head](https://user-images.githubusercontent.com/9607060/120992463-4c55b900-c78b-11eb-9b51-d906190ba6d6.png)

2021-06-07 09:28 UTC, aleksfront commented on src/renderer/themes/lens-light.json
> +    "clusterMenuBackground": "#c3c3c3",
```suggestion
    "clusterMenuBackground": "#d7d8da",
```

2021-06-08 07:02 UTC, aleksfront approved these changes

2021-06-08 07:03 UTC, merged