Rollout support
lensapp/lens pull request #3536
Opened 2021-07-30 09:51 UTC by vshakirova

currently, I'm working on this issue https://github.com/lensapp/lens/issues/498 and if I'm not mistaken each resource (statefulset/deployment/daemonset) has the same implementation. And I think it may be useful to create smth general for this purpose. As a draft, I did it for `Scale` since it also has a code duplication. Then I'm going to do it for restart/history/e.t.c..
Okay, guys, I'm absolutely not sure about my approach and it may look disgusting but does it make sense? Thanks in advance

2021-08-03 08:06 UTC, aleksfront commented
@vshakirova I don't see anything bad with your design. Just thinking if we can move duplicated parts of rollout methods into separate `abstract` class, say `WorkloadKubeApi`. To avoid copypasting `restart`, `undo`, `history` and other commands.

So `DeploymentApi` can be declared like this
```
export class DeploymentApi extends WorkloadKubeApi<Deployment> {}
```

2021-08-03 08:09 UTC, aleksfront commented on src/renderer/components/+workloads/rollout-menu.tsx
> +export function renderRestart<T extends WorkloadKubeObject>(workloadKubeObject: T, api: any, interactive?: boolean) {
I guess we need to provide some information to `api` argument type, not `any`

2021-08-03 08:09 UTC, aleksfront commented on src/renderer/components/+workloads/rollout-menu.tsx
> +  }
This can be removed. Check is already done in parent `RolloutMenu` component.

2021-08-03 08:09 UTC, aleksfront commented on src/renderer/components/+workloads/rollout-menu.tsx
> +}
This should be moved to separate component as all of the rollout commands will share exact same code.

2021-08-26 09:43 UTC, vshakirova commented on src/renderer/components/+workloads/rollout-menu.tsx
> +export function renderRestart<T extends WorkloadKubeObject>(workloadKubeObject: T, api: any, interactive?: boolean) {
Yeah, everything did not go according to plan) 
Different resources have similar logic, but not the same.

2021-09-02 16:59 UTC, vshakirova commented on src/common/k8s-api/endpoints/controller-revision.api.ts
> +export class ControllerRevision extends WorkloadKubeObject {
I will change it to KubeObject

2021-09-14 13:34 UTC, Nokel81 requested changes
Start of a review

2021-09-14 13:34 UTC, Nokel81 commented on src/common/k8s-api/endpoints/controller-revision.api.ts
> +});
This will need to be updated to be like the other ones. Such as in `pods.api.ts`

2021-09-14 13:34 UTC, Nokel81 commented on src/common/k8s-api/endpoints/daemon-set.api.ts
> +}
Why was this changed?

2021-09-14 13:34 UTC, Nokel81 commented on src/common/k8s-api/endpoints/deployment.api.ts
> -          }
Please revert, this is a breaking change.

2021-09-14 13:34 UTC, Nokel81 commented on src/common/k8s-api/endpoints/replica-set.api.ts
> +    return parseInt(this.metadata.annotations[revisionAnnotation]);
Do we really want to return `NaN` if that annotation is missing?

2021-09-14 13:34 UTC, Nokel81 commented on src/common/k8s-api/endpoints/stateful-set.api.ts
> +export class StatefulSetApi extends WorkloadKubeApi<StatefulSet> {
Why are you changing these?

2021-09-14 13:34 UTC, Nokel81 commented on src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
> +    }) as ControllerRevision[];
This cast should be unnecessary `getRevisions`'s return type should be `ControllerRevision[] | null`

2021-09-14 13:34 UTC, Nokel81 commented on src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
> +    this.revisionHistory = observable.array(revisionHistory);
This is redundent, please change to `this.revisionHistory.replace(revisionHistory)`

2021-09-14 13:34 UTC, Nokel81 commented on src/renderer/components/+workloads-daemonsets/daemonsets.tsx
> +  );
nit

```suggestion
  return <RolloutMenu workloadKubeObject={object}/>;
```

2021-09-14 13:34 UTC, Nokel81 commented on src/renderer/components/+workloads-deployments/deployments.store.ts
> +  }
Would you mind doing this in a different PR? I don't see why it is necessary for rollout support.

2021-09-14 13:34 UTC, Nokel81 commented on src/renderer/components/+workloads-deployments/deployment-details.tsx
> -        <DeploymentReplicaSets replicaSets={replicaSets}/>
Do we no longer have replica sets?

2021-10-21 06:24 UTC, vshakirova commented on src/common/k8s-api/endpoints/daemon-set.api.ts
> +}
Scale and restart work similar for daemontSet/DeploymentSet/Statetfulset. It is just an attempt to get rid of duplicate code. I've moved `Restart` functionality to `WorkloadKubeApi` abstract class.

2021-10-21 06:26 UTC, vshakirova commented on src/common/k8s-api/endpoints/deployment.api.ts
> -          }
we still have restart functionality, because we extend `WorkloadKubeApi`. These are just additional functions.

2021-10-21 06:27 UTC, vshakirova commented on src/common/k8s-api/endpoints/stateful-set.api.ts
> +export class StatefulSetApi extends WorkloadKubeApi<StatefulSet> {
My intention was to get rid of duplicate code

2021-10-21 07:21 UTC, vshakirova commented on src/renderer/components/+workloads-daemonsets/daemonsets.tsx
> +  );
much better, thank you!

2021-10-21 11:47 UTC, vshakirova commented on src/renderer/components/+workloads-deployments/deployment-details.tsx
> -        <DeploymentReplicaSets replicaSets={replicaSets}/>
We have, I just rename it because it seems like here (https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/rollback.go#L212) they get a list of replicaSets and chose appropriate for rollback. I guess there is no need to duplicate the same information.

2021-10-21 11:48 UTC, vshakirova commented on src/renderer/components/+workloads-deployments/deployments.store.ts
> +  }
yes of course, I'll revert it

2021-10-21 11:56 UTC, vshakirova commented on src/common/k8s-api/endpoints/replica-set.api.ts
> +    return parseInt(this.metadata.annotations[revisionAnnotation]);
Agree. Maybe `parseInt(this.metadata.annotations[revisionAnnotation]) || ""`. Wdyt?

2021-10-21 18:23 UTC, Nokel81 commented on src/common/k8s-api/endpoints/replica-set.api.ts
> +    return parseInt(this.metadata.annotations[revisionAnnotation]);
Given that this is only really used for display, I don't see the benefit of parsing at all. That way we could display `"-"` when missing.

2021-10-26 21:32 UTC, Nokel81 commented on src/common/k8s-api/endpoints/stateful-set.api.ts
> +export class StatefulSetApi extends WorkloadKubeApi<StatefulSet> {
Okay that seems fair, I would have made a free function that such methods could just call instead.

2021-10-26 21:33 UTC, Nokel81 commented on src/renderer/components/+workloads-deployments/deployment-revision-history.tsx
> +  object: ReplicaSet[];
why the rename? Also if it is a list then the parameter should be plural

2021-10-26 21:34 UTC, Nokel81 commented on src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
> +    this.revisionHistory = observable.array(revisionHistory);
nit: could be
```suggestion
    this.revisionHistory.replace(await controllerRevisionApi.getRevisions({
      name: statefulSet.getName(),
      namespace: statefulSet.getNs()
    }));
```

2021-10-26 21:37 UTC, Nokel81 commented on src/renderer/components/+workloads/workload-rollback-dialog.tsx
> +    TerminalStore.getInstance().sendCommand(`kubectl rollout undo ${this.workloadKubeObject.kind.toLocaleLowerCase()}` +
why `toLocaleLowerCase()`? even more `kubectl` accepts kind directly it seems.

2021-10-27 13:55 UTC, vshakirova commented on src/common/k8s-api/endpoints/stateful-set.api.ts
> +export class StatefulSetApi extends WorkloadKubeApi<StatefulSet> {
I can change my approach, but what do you mean by saying 'free function'?

2021-10-27 13:59 UTC, Nokel81 commented
Plan to try and finish a better and more complete review today, would be great if you could rebase.

2022-03-23 12:56 UTC, Nokel81 commented
Marking as draft since it has been few months since this was last worked on.

2022-11-10 15:15 UTC, Nokel81 commented
Closing as this is out of date and has not been updated in a long time. Please feel free to reopen if/when you have time.

2022-11-10 15:15 UTC, closed without merging