Add Copy object name feature to the menu
lensapp/lens pull request #3575
Opened 2021-08-06 05:39 UTC by mostafahussein

This PR makes it easier to copy any of the pod names , configmaps and so on by adding a button to the k8s object menu

2021-08-12 09:01 UTC, aleksfront requested changes
@mostafahussein Thanks for contribution! Your addition can be really useful, but it needs to have some of the UI/UX changes.

Separate menu `Copy` menu item may be omitted because it doesn't clearly show what exactly getting copied here. By clicking `Copy`, the pod itself can be copied in some way, it's contents, the name etc.

Instead, it's good to add copy button next to resource (Pod, Deployment, Secret, etc) which will appear on mouse hover.

![place for copy button](https://user-images.githubusercontent.com/9607060/129169206-288a54b4-bebe-45e6-a399-1e0daae69e62.gif)

Is it possible to implement this change?

2021-08-14 08:11 UTC, mostafahussein commented
Hello @aleksfront, thank you for your feedback, I have moved the copy functionality as suggested, can you review it again please?

2021-08-16 07:59 UTC, aleksfront reviewed
Added few style-related comments which will allow icon to look like this
![copy button](https://user-images.githubusercontent.com/9607060/129530577-dd7628cc-271c-4de9-ae1c-c109e6a0d347.gif)

Also, would be nice if click event will trigger tooltip to be `Copied` instead of `Copy` to say user that feature worked as expected. This can be done by replacing `Copy` -> `Copied` in Icon `onClick` event, and then replacing back `Copied` -> `Copy` in `<div className="drawer-title-text">` `onMouseOut` event.

2021-08-16 07:59 UTC, aleksfront commented on src/renderer/components/drawer/drawer.tsx
> +              <div className="drawer-title-text">
Add some extra class names to make sure copy icon will be placed correctly with some super-long object name


```
<div className="drawer-title-text flex gaps align-center">
```

2021-08-16 07:59 UTC, aleksfront commented on src/renderer/components/drawer/drawer.scss
> +    }
Some fine-tuning needed to make sure our copy icon looks good. The main thing here is to replace `visibility` prop with `opacity` to make it possible to animate transition on hover.


```
.drawer-title-text .Icon {
  opacity: 0;
  font-weight: normal;
  margin-left: 8px;
}
 
.drawer-title-text:hover .Icon {
  opacity: 1;
  transition: opacity 250ms;
}
```

2021-08-16 13:29 UTC, mostafahussein commented
@aleksfront , thanks, that was really helpful. The requested changes are done.

Regarding changing the tooltip suggestion, I decided to implement it similar to what Github is doing when you copy the branch name.

- The icon will change to "done"
- The tooltip will change to "Copied!"
- Everything will be reverted to its original state based on "setTimeOut" instead of using "onMouseOut" event.
- 
What do you think?

2021-08-17 04:50 UTC, mostafahussein commented
@aleksfront , thanks, that was really helpful. The requested changes are done.

Regarding what should happen when you click the copy button, I decided to implement it similar to what Github is doing when you copy the branch name or file path.

- The icon will be changed to "done"
- The tooltip will be changed to "Copied!"
- Everything will be reverted to its original state based on setTimeOut instead of using onMouseOut event.

What do you think?

2021-08-17 10:41 UTC, aleksfront commented on src/renderer/components/drawer/drawer.tsx
> +    }, 400);
Please increase timeout to 3 or 4 seconds. Now it changes too fast:
![fast copy button](https://user-images.githubusercontent.com/9607060/129712133-f4a7062d-4d7d-4637-a917-61b1f562d1bd.gif)

2021-08-17 10:42 UTC, aleksfront commented on src/renderer/components/drawer/drawer.tsx
> +    const copyTooltip = isCopied? "Copied!" : "Copy";
We can create also `copyIcon` constant here to keep component state clean (only with 1 value `isCopied`).

2021-08-17 10:42 UTC, aleksfront commented
@mostafahussein Added a few tiny comments, please take a look. Otherwise, looks good!

2021-08-17 11:27 UTC, mostafahussein commented
@aleksfront  all done 🎉 ,  you can check it now

2021-08-17 12:44 UTC, aleksfront commented
There's 2 linter errors over there. Please run `yarn lint:fix`.

2021-08-17 14:05 UTC, aleksfront approved these changes
Looking good!

2021-08-17 14:05 UTC, merged