Fix accessible namespaces notification not navigating to correct settings
lensapp/lens pull request #4048
Opened 2021-10-14 18:57 UTC by Nokel81

- Cleaned up the broadcasting of failure to that the debounding is only
  on renderer. This leads to faster initial notification.

- Improved logging to not log entire request.Response object

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4034

2021-10-14 20:04 UTC, Nokel81 commented
FYI This doesn't actually fix all the bugs in this because we can no longer scroll into view a sub-setting. I think we should switch this to something similar to what https://github.com/lensapp/lens/pull/3573 did from user preferences.

2021-10-15 10:42 UTC, aleksfront requested changes
All good instead need to fix `Proxy` to `proxy` in `cluster-status.ts`.

```
manageProxySettings = () => {
    navigate(entitySettingsURL({
      params: {
        entityId: this.props.clusterId,
      },
      fragment: "proxy",
    }));
  };
```

Minor but cluster status link doesn't work properly.

2021-10-15 12:36 UTC, Nokel81 commented
@aleksfront Fixed, WDYT about a future where the top level menus are routes?

2021-10-15 12:37 UTC, aleksfront commented
> @aleksfront Fixed, WDYT about a future where the top level menus are routes?

Sure it should be done as in Preferences page.

2021-10-15 12:38 UTC, aleksfront approved these changes

2021-10-15 13:06 UTC, merged