Navigate cluster context menus via broadcastMessage
lensapp/lens pull request #4139
Opened 2021-10-26 08:11 UTC by aleksfront

Part 1 of 2 PRs in order to fix #4088 

Extension should navigate to `Settings` no matter where this action triggered - in hotbar menu or from in-cluster view.

Should be merged along with https://github.com/lensapp/lenscloud-lens-extension/pull/812

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

2021-10-26 13:18 UTC, Nokel81 requested changes
No this is incorrect because you might what to navigate in the cluster too

2021-10-27 07:29 UTC, aleksfront commented
> No this is incorrect because you might what to navigate in the cluster too

Added `inMainFrame` flag to choose frame to navigate. @Nokel81 ptal.

2021-10-27 13:13 UTC, Nokel81 commented on src/renderer/components/layout/sidebar.tsx
> +    navigate: (url: string, inMainFrame = true) => {
I would call this `forceTopLocation` or something because `navigate("/settings", false)` will still work if called in the main frame.

2021-10-27 14:43 UTC, aleksfront commented on src/renderer/components/layout/sidebar.tsx
> +    navigate: (url: string, inMainFrame = true) => {
Ended up with `forceMainFrame`.

2021-10-27 14:45 UTC, Nokel81 approved these changes
Should we do this for every context? Maybe by having a helper function that creates the context?

2021-10-28 03:50 UTC, merged