fix: use non-deprecated delete flag with node drain
lensapp/lens pull request #4400
Opened 2021-11-21 23:35 UTC by laebshade

# Problem

`kubectl drain` calls a deprecated flag, `--delete-local-data`, per https://github.com/kubernetes/kubernetes/pull/95076.

# Solution

Use the designated replacement.

# Result

No warning errors about the `--delete-local-data` flag deprecation on node drain.

2021-11-22 00:30 UTC, Nokel81 approved these changes

2021-11-22 00:31 UTC, Nokel81 requested changes
This might not exist on older versions of kubectl. This should be changed depending on the version.

2021-11-22 00:38 UTC, laebshade commented
> This might not exist on older versions of kubectl. This should be changed depending on the version.

Ok. What changes are you specifically looking for?

2021-11-22 14:38 UTC, Nokel81 commented
@laebshade Yes they are not supported but we download an appropriate kubectl version based on the kube version of a cluster.

So I would get the active entity in that menu, look at the kube version metadata and switch which arg is used based on that.

2021-11-22 18:13 UTC, laebshade commented
Thanks for clarifying.

I’m unable to prioritize your requested changes.

Do you wish to close this PR, pick up ownership, or hand off your requested
changes to some one else specifically?

On Mon, Nov 22, 2021 at 9:38 AM Sebastian Malton ***@***.***>
wrote:

> @laebshade <https://github.com/laebshade> Yes they are not supported but
> we download an appropriate kubectl version based on the kube version of a
> cluster.
>
> So I would get the active entity in that menu, look at the kube version
> metadata and switch which arg is used based on that.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/lensapp/lens/pull/4400#issuecomment-975595024>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABAKQ4KOSOJ5QVZ2OVHK7X3UNJIXBANCNFSM5IPWRQ2Q>
> .
>

2021-11-22 19:01 UTC, Nokel81 commented
If you are unable to spend the time now, could you open an issue describing this issue before you close the PR. That way we can track it for planning.

2021-11-23 23:43 UTC, laebshade commented
No thank you

On Mon, Nov 22, 2021 at 2:01 PM Sebastian Malton ***@***.***>
wrote:

> If you are unable to spend the time now, could you open an issue
> describing this issue before you close the PR. That way we can track it for
> planning.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lensapp/lens/pull/4400#issuecomment-975828152>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABAKQ4M3S527DZAHWHFONXLUNKHQVANCNFSM5IPWRQ2Q>
> .
>

2021-11-25 17:08 UTC, closed without merging