Replace KubeObjectDetailRegistry with injectable version
lensapp/lens pull request #4631
Opened 2022-01-05 20:40 UTC by Nokel81

Signed-off-by: Sebastian Malton <sebastian@malton.name>

2022-01-05 20:40 UTC, Nokel81 commented on package.json
> +      "^monaco-editor": "<rootDir>/node_modules/monaco-editor"
This mock is required so that jest won't complain about trying to load it.

2022-01-11 13:00 UTC, jansav requested changes

2022-01-11 13:00 UTC, jansav commented on src/renderer/components/kube-object-details/kube-details-items/kube-details.injectable.ts
> +  instantiate: di => computed(() => {
Let's separate implementation to separate file. Just to keep `di` out from implementation. 
Sometimes implementation is so trivial that it doesn't make sense to create new file for it, but in this case it isn't.

2022-01-19 20:20 UTC, Nokel81 commented
Closing in favour of #4717

2022-01-19 20:20 UTC, closed without merging