Fix not being able to install extensions sometimes
lensapp/lens pull request #4794
Opened 2022-02-02 13:47 UTC by Nokel81

- Specifically, when there are remnants of a previous install of the
  extension which caused the code to be confused and enter the wrong
  branch

Signed-off-by: Sebastian Malton <sebastian@malton.name>

2022-02-03 09:00 UTC, aleksfront commented
Please try to test with https://github.com/nevalla/lens-resource-map-extension/releases. Inside this branch it's stuck in unpacking step.
<img width="1440" alt="freeze in unpacking" src="https://user-images.githubusercontent.com/9607060/152311565-1cb7c8bf-d30b-4872-a0a0-12534b4eb478.png">


(I'm using alpha link on screenshot, but same goes for stable version).

On `master`, unpacking goes okay, however extension won't get installed because of other errors.

2022-02-03 09:14 UTC, aleksfront commented
Also, this happens in master also, but can't install extension by its npmjs name
<img width="1436" alt="no install from npm" src="https://user-images.githubusercontent.com/9607060/152313604-f0bcbc47-f660-4e11-a298-8c7cd9173168.png">

2022-02-03 11:39 UTC, jansav requested changes

2022-02-03 11:39 UTC, jansav commented on src/renderer/components/+extensions/attempt-install/attempt-install.tsx
> +      const installedExtensionsion = extensionLoader.getExtension(validatedRequest.id);
typo 

```suggestion
      const installedExtension = extensionLoader.getExtension(validatedRequest.id);
```

2022-02-03 11:39 UTC, jansav commented on src/renderer/components/+extensions/attempt-install/attempt-install.tsx
> +      if (installedExtensionsion) {
```suggestion
      if (installedExtension) {
```

2022-02-03 11:39 UTC, jansav commented on src/renderer/components/+extensions/attempt-install/attempt-install.tsx
> +        const { version: oldVersion } = installedExtensionsion.manifest;
```suggestion
        const { version: oldVersion } = installedExtension.manifest;
```

2022-02-03 14:49 UTC, Nokel81 commented
> 

@aleksfront Using the latest `.tgz` file link I was able to install easily and without too much delay.

2022-02-03 14:49 UTC, Nokel81 commented
@jansav PTALA, I have fixed the typo

2022-02-04 04:50 UTC, aleksfront commented
@Nokel81 I don't know the exact reason but it's still stuck in `unpacking` step for me. However, it seems that some files appeared in `.k8slens/extensions` folder. See below:

https://user-images.githubusercontent.com/9607060/152473691-4bbe93cf-cb98-4078-8c52-ead57c568441.mov

2022-02-04 06:10 UTC, jansav approved these changes

2022-02-07 11:12 UTC, ixrock approved these changes

2022-02-07 14:07 UTC, merged