Ingress metrics fix for namespace
lensapp/lens pull request #4906
Opened 2022-02-21 09:47 UTC by kamilgregorczyk

https://github.com/lensapp/lens/issues/4348

The namespace label for ingress metrics is set to the controller namespace. The actual ingress namespace is in the exported_namespace label.

2022-02-21 10:07 UTC, aleksfront commented
@kamilgregorczyk Please sign-off your commits. See https://github.com/lensapp/lens/pull/4906/checks?check_run_id=5272052560

2022-02-23 13:38 UTC, ixrock approved these changes

2022-03-09 13:35 UTC, aleksfront commented
https://github.com/lensapp/lens/issues/4348#issuecomment-1062846084

2022-07-10 20:52 UTC, maxpain commented
Any updates?

2022-08-02 11:37 UTC, m00nyONE commented
any Updates on this?

2022-08-04 17:01 UTC, Nokel81 commented
This is sort of blocked on #3955

2022-10-07 22:04 UTC, Nokel81 requested changes
Thanks for the proposal, but since the request from https://github.com/lensapp/lens/issues/4348#issuecomment-1062846084 hasn't been responded to, I don't think we should merge this.

I am having trouble verifying either since prometheus never seems to get any metrics from the nginx-ingress-controller.

2023-04-24 13:48 UTC, Nokel81 commented
Closing as out of date.

2023-04-24 13:48 UTC, closed without merging