Make terminal tab icon the same as the menu item icon
lensapp/lens pull request #5449
Opened 2022-05-25 19:35 UTC by Nokel81

Just something off than I noticed.

Signed-off-by: Sebastian Malton <sebastian@malton.name>

before:
![Screen Shot 2022-05-25 at 3 33 43 PM](https://user-images.githubusercontent.com/8225332/170353055-561e0e61-0e98-4454-b26b-b89825d0de6a.png)

after:
![Screen Shot 2022-05-25 at 3 32 07 PM](https://user-images.githubusercontent.com/8225332/170353082-aec3cd06-fe34-4f11-881f-2fc297166415.png)

2022-05-26 12:47 UTC, aleksfront requested changes
I would invert your change and use material icon version inside the `Terminal` menu item. Svg version is non-standart and was introduced by the times when material icons haven't got own `terminal` icon yet.

Svg terminal icon would be eliminated for the next major version.

2022-05-26 13:14 UTC, Nokel81 commented
@aleksfront Here is how it looks with your recommendations
![Screen Shot 2022-05-26 at 9 14 17 AM](https://user-images.githubusercontent.com/8225332/170494834-18a22e8d-a632-408e-a9f8-25c0f4888e09.png)

2022-05-26 13:52 UTC, aleksfront approved these changes

2022-05-30 15:30 UTC, ixrock approved these changes

2022-05-30 15:31 UTC, merged