add css variable changing for 'clusters-menu-bgc'
lensapp/lens pull request #625
Opened 2020-07-30 20:39 UTC by Nokel81

Signed-off-by: Sebastian Malton <smalton@mirantis.com>

2020-08-02 12:37 UTC, ixrock commented on src/renderer/themes/kontena-light.json
> +    "clusters-menu-bgc": "#afafaf",
Should be `camelCase`-d as other names

2020-08-02 12:38 UTC, ixrock approved these changes

2020-08-02 12:39 UTC, ixrock requested changes

2020-08-02 12:39 UTC, ixrock commented on src/renderer/themes/theme-vars.scss
> +$clusters-menu-bgc: var(--clusters-menu-bgc);
Here as well

2020-08-20 07:12 UTC, nevalla approved these changes
LGTM

2020-08-20 07:16 UTC, nevalla commented
@Nokel81 Is still relevant? If yes, feel free to merge after changing the target branch.

2020-08-20 08:18 UTC, aleksfront commented
My guess it can be closed since I do a bit of refactoring in cluster menu and other places. Some colors/vars will be changed.

2020-08-20 11:23 UTC, nevalla commented
Okay. I'm closing this now. Let's re-open if required.

2020-08-20 11:23 UTC, closed without merging