Clickable links in pods details for ServiceAccount, PriorityClass and RuntimeClass
lensapp/lens pull request #6352
Opened 2022-10-07 10:42 UTC by dex4er

This is a small improvement for pod details:

![image](https://user-images.githubusercontent.com/174367/194535069-55eae4d7-6a88-4b2a-a5fe-9f3fbdc7b641.png)

Links to ServiceAccount, PriorityClass and RuntimeClass are clickable and move to the details of the chosen resource.

2022-10-07 13:31 UTC, Nokel81 requested changes
Thanks for doing this work, just a minor request.

2022-10-07 13:31 UTC, Nokel81 commented on src/renderer/components/+workloads-pods/pod-details.tsx
> +    }));
Given that `PodDetails` already has been made to use injectables via `withInjectables`. I would prefer if these were not introduced a globals but instead passed in using `withInjectables`.

To do that you should:
1. Add these three apis to the `Dependencies` type above
2. Add `priorityClassApi: di.inject(priorityClassApiInjectable)`, etc... to the `withInjectables` call below
3. Change the usage to `this.props.priorityClassApi`, etc ...

2022-10-09 22:32 UTC, dex4er commented on src/renderer/components/+workloads-pods/pod-details.tsx
> +    }));
Ok. Done.

2022-10-11 12:43 UTC, Nokel81 commented
@dex4er Please resolve lint issues and then this LGTM

2022-10-11 14:03 UTC, Nokel81 approved these changes

2022-10-11 14:04 UTC, merged

2022-10-11 14:04 UTC, Nokel81 commented
@dex4er Thanks again!

2022-10-11 14:04 UTC, dex4er commented
@Nokel81 Linter clean. I forgot there is `npm run lint:fix`