Set correct group in rbac
lensapp/lens pull request #6880
Opened 2023-01-05 12:47 UTC by farodin91

Fixes #6879

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

2023-01-05 13:01 UTC, Nokel81 approved these changes

2023-01-05 13:01 UTC, Nokel81 commented
Thanks!

2023-01-05 13:35 UTC, Nokel81 requested changes
Actually there is slightly more work to do.

Can you also change the relevant uses of `di.inject(shouldShowResourceInjectionToken, { ...`?

For instance there is one in `src/common/front-end-routing/routes/cluster/config/config-maps/config-maps-route.injectable.ts` that should be updated too.

2023-01-05 13:48 UTC, farodin91 commented
@Nokel81  I hope caught all.

2023-01-05 13:52 UTC, Nokel81 commented on src/renderer/components/+workloads-overview/workloads/implementations/pods-workload.injectable.ts
> +        group: ",
missing a `"` I think

2023-01-05 13:52 UTC, Nokel81 commented
Also please sign your commit. Thanks for the fast response

2023-01-05 13:53 UTC, farodin91 commented
@Nokel81 done

2023-01-05 13:54 UTC, Nokel81 approved these changes, later dismissed

2023-01-05 14:31 UTC, Nokel81 commented
Might have to fix the tests too

2023-01-05 14:32 UTC, farodin91 commented
i will try to fix it tomorrow.

2023-01-05 14:33 UTC, Nokel81 commented
I think it will be as simple as to just remove the `"v1"` in the tests too

2023-01-05 15:34 UTC, Nokel81 approved these changes

2023-01-05 16:05 UTC, farodin91 commented
@Nokel81 i have no idea why the missing tests are failing.

2023-01-05 16:07 UTC, Nokel81 commented
I can investigate

2023-01-05 21:08 UTC, Nokel81 commented
I noticed that this doesn't entirely solve the issue. Will look again on Monday.

2023-01-09 15:01 UTC, Nokel81 commented
@farodin91 if you run kubectl get --raw /api you should get back a JSON object that has a field called versions. What is its value? On GKE and minikube it is ["v1"]

2023-01-09 15:19 UTC, farodin91 commented
I get the same value.

2023-01-11 14:02 UTC, closed without merging