Generate tray icons on a schedule
lensapp/lens pull request #7098
Opened 2023-02-02 17:39 UTC by Nokel81

Signed-off-by: Sebastian Malton <sebastian@malton.name>

2023-02-02 17:46 UTC, jim-docker submitted a review, later dismissed

2023-02-02 19:37 UTC, jim-docker approved these changes, later dismissed

2023-02-02 21:24 UTC, jim-docker approved these changes

2023-02-03 08:04 UTC, jansav commented
Why do we need something like this?

2023-02-03 08:23 UTC, Iku-turso requested changes
As @jansav said, the motivation for this PR is unclear.

2023-02-03 11:32 UTC, Nokel81 commented
This is not needed due to https://github.com/lensapp/lens/pull/7101

2023-02-03 11:32 UTC, closed without merging