Respect cluster avatars entity background color
lensapp/lens pull request #7365
Opened 2023-03-16 13:23 UTC by aleksfront

Second part of #3846 

First part https://github.com/lensapp/lens/pull/7349

All cluster icons updated if `backgroundColor` changed in cluster preferences.

<img width="349" alt="salmon cluster 1" src="https://user-images.githubusercontent.com/9607060/225630103-95f889f0-26ca-48ab-b96b-1c38a386fbeb.png">
<img width="999" alt="salmon cluster 2" src="https://user-images.githubusercontent.com/9607060/225630105-97a1ae5f-472d-4071-974c-928122125c8f.png">
<img width="923" alt="salmon cluster 3" src="https://user-images.githubusercontent.com/9607060/225630109-33ff397f-0161-44a9-a948-c2fbb4d74e76.png">

2023-03-16 13:39 UTC, ixrock requested changes

2023-03-16 13:39 UTC, ixrock commented on packages/core/src/common/cluster-types.ts
> +  iconBackgroundColor?: string;
Why do we need another field for `icon`? It's possible I guess to save some `string` with color (HEX/rgba) to `icon` field too and distinguish them easily (when it's not empty) by `prefs.icon.startsWith("data:")` to proper show background.

2023-03-16 13:39 UTC, ixrock commented on packages/core/src/renderer/components/hotbar/hotbar-entity-icon.tsx
> +  getClusterById: (id: string) => Cluster | undefined;
Why this is here? I haven't found usages of `getClusterById` in  other files..

2023-03-16 15:27 UTC, Nokel81 approved these changes

2023-03-17 10:25 UTC, ixrock approved these changes

2023-03-17 10:50 UTC, merged