Support using Eviction API where applicable
lensapp/lens pull request #7372
Opened 2023-03-17 13:25 UTC by ixrock

close #5602

2023-03-17 18:33 UTC, Nokel81 reviewed
would be great if there were a couple unit tests to make sure that future changes to this code don't accidently break the findings here.

2023-03-17 18:33 UTC, Nokel81 commented on packages/core/src/common/k8s-api/kube-object.ts
> +    this.status = data.status || "";
won't these `|| ""` break the `??` used bellow?

2023-03-20 17:46 UTC, Nokel81 commented
Also reminder that enhancements should never go into patch releeases

2023-03-21 07:53 UTC, aleksfront approved these changes, later dismissed

2023-03-21 14:13 UTC, Nokel81 requested changes

2023-03-21 14:13 UTC, Nokel81 commented on packages/core/src/common/k8s-api/endpoints/pod.api.ts
> +  async evict(resource: DeleteResourceDescriptor) {
Need to have some unit tests for this change

2023-03-22 10:18 UTC, ixrock commented on packages/core/src/common/k8s-api/kube-object.ts
> +    this.status = data.status || "";
Hmm.. I think you're right. Gonna update this.

2023-03-23 14:12 UTC, jim-docker reviewed
In light of https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/#troubleshooting-stuck-evictions we might want to support a "force delete" option in the Lens UI, which directly invokes the delete() method instead of evict(). Could be for another PR...

2023-03-23 14:12 UTC, jim-docker commented on packages/core/src/renderer/components/kube-object-menu/kube-object-menu.tsx
> -  removable?: boolean;
This is just unrelated refactoring?

2023-03-23 14:58 UTC, ixrock commented on packages/core/src/renderer/components/kube-object-menu/kube-object-menu.tsx
> -  removable?: boolean;
Reverted

2023-03-23 15:00 UTC, ixrock commented
> In light of https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/#troubleshooting-stuck-evictions we might want to support a "force delete" option in the Lens UI, which directly invokes the delete() method instead of evict(). Could be for another PR...

How exactly you think we should implement it? Keep separated menu items "Delete" and "Evict" for the Pods menu?

2023-03-23 15:02 UTC, ixrock commented on packages/core/src/common/k8s-api/endpoints/pod.api.ts
> +  async evict(resource: DeleteResourceDescriptor) {
Done. PTAL

2023-03-23 15:08 UTC, Nokel81 approved these changes
LGTM!

2023-03-23 16:16 UTC, merged

2023-03-23 16:17 UTC, Nokel81 commented
> How exactly you think we should implement it? Keep separated menu items "Delete" and "Evict" for the Pods menu?

Maybe we could somehow detect that a pod is being evicted and then show a `Force Delete` action in the menu.

2023-03-23 20:44 UTC, jim-docker commented
> > How exactly you think we should implement it? Keep separated menu items "Delete" and "Evict" for the Pods menu?
> 
> Maybe we could somehow detect that a pod is being evicted and then show a `Force Delete` action in the menu.

I thought of separate menu items. "Delete" (or "Evict") and "Force Delete" (or "Kill"). Also, there could be a "Force" checkbox on the delete dialog.