no updates available
lensapp/lens pull request #7390
Opened 2023-03-21 09:02 UTC by gabriel-mirantis

2023-03-21 13:38 UTC, aleksfront approved these changes, later dismissed

2023-03-21 14:13 UTC, Nokel81 requested changes
Adding some behavioural tests would be great!

2023-04-03 18:11 UTC, gabriel-mirantis commented
> Adding some behavioural tests would be great!

check

2023-04-03 18:17 UTC, Nokel81 approved these changes
LGTM!

Will merge once tests are green

2023-04-03 19:36 UTC, merged